<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Sales by Person Report</title>
    <style>
        body { font-family: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-size: 10pt; color: #333; margin: 0; padding: 0; }
        .header { border-bottom: 2px solid #eee; padding-bottom: 15px; margin-bottom: 20px; }
        .title { font-size: 18pt; font-weight: bold; margin: 0; }
        .meta { font-size: 9pt; color: #666; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        th { background: #f8f9fa; text-align: left; padding: 10px; border-bottom: 2px solid #dee2e6; font-size: 9pt; text-transform: uppercase; }
        td { padding: 10px; border-bottom: 1px solid #dee2e6; font-size: 9pt; }
        .amount { text-align: right; font-weight: bold; }
        .total-row { background: #f8f9fa; font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 8pt; color: #999; padding: 10px 0; }
    </style>
</head>
<body>
    <div class="header">
        <table style="border: none; margin-bottom: 0;">
            <tr style="border: none;">
                <td style="border: none; padding: 0;">
                    <h1 class="title">SALES BY PERSON REPORT (POS)</h1>
                    <div class="meta">
                        Period: {{ $startDate->format('d M, Y') }} - {{ $endDate->format('d M, Y') }}<br>
                        Generated: {{ now()->format('d M, Y h:i A') }}
                    </div>
                </td>
            </tr>
        </table>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Invoice</th>
                <th>Staff Member</th>
                <th>Customer</th>
                <th style="text-align: right;">Amount (AED)</th>
            </tr>
        </thead>
        <tbody>
            @foreach($orders as $order)
            <tr>
                <td>{{ $order->created_at->format('d M, Y') }}</td>
                <td>{{ $order->invoice_no }}</td>
                <td>{{ $order->user->name ?? 'System' }}</td>
                <td>{{ $order->customer_name }}</td>
                <td class="amount">{{ number_format($order->total, 2) }}</td>
            </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr class="total-row">
                <td colspan="4" style="text-align: right;">TOTAL POS SALES</td>
                <td class="amount">{{ number_format($totalSales, 2) }}</td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by {{ config('app.name') }}
    </div>
</body>
</html>
